# ==========================================
# 🔐 CREDENTIALS
# ==========================================
CLIENT_ID = "6LV74LVY1F-100"      
SECRET_KEY = "NAWBTNX48Q"
REDIRECT_URI = "http://127.0.0.1:5000/redirect"

# This reads the token generated by your Notebook so you don't have to copy-paste it.
try:
    # Look for token in data/access_token.txt
    token_path = os.path.join(os.getcwd(), "data", "access_token.txt")
    with open(token_path, "r") as f:
        ACCESS_TOKEN = f.read().strip()
except FileNotFoundError:
    print("⚠️ WARNING: Access Token file not found. Run the Notebook first!")
    ACCESS_TOKEN = None

# ==========================================
# ⚙️ STRATEGY SETTINGS
# ==========================================
TICKER = "NSE:SONATSOFTW-EQ" 
START_DATE_DATA = "2025-06-01"
BACKTEST_START = "2025-11-01"
BACKTEST_END = "2025-12-31"

# Model Hyperparameters
CONFIDENCE_THRESHOLD = 0.55
TARGET_VOL = 0.20
MAX_LEVERAGE = 2.0
